export const NotificationType = {
  TASK_UPDATE: 'TASK_UPDATE',
  TASK_COMMENT: 'TASK_COMMENT',
  TASK_ASSIGN: 'TASK_ASSIGN',
  TASK_OVERDUE: 'TASK_OVERDUE',
  TASK_UNASSIGN: 'TASK_UNASSIGN',
  PROJECT_INVITE: 'PROJECT_INVITE',
  PROJECT_REMOVE_MEMBER: 'PROJECT_REMOVE_MEMBER',
};
